openapi: 3.0.0
info:
  version: 0.2.1
  title: Software de testes
  description: Projeto para o 3º semestre do CT Desenvolvimento de Sistemas. <br>Software para gerenciamento de mesa inteligente desenvolvida para a empresa TAIFF.
  
servers:
  - url: http://localhost:8080
    description: Servidor para o consumo dos end-points
paths:
  /posicao/teste/{produtoNome}:
    get:
      tags:
        - "Testes"
      summary: "Busca os testes pelo nome do produto"
      description: "Busca todos os testes referentes ao produto"
      parameters:
        - name: produtoNome
          in: path
          required: true
          description: Parameter description in CommonMark or HTML.
          schema:
            type: string
            format: utf-8
            minimum: 1
      responses: 
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/testesArray'
        '404':           
          description: Não encontrado
        '400':
          description: Valor inválido
        '500':
          description: Falha na comunicação com o servidor
          
  /posicao/teste/{id}:
    put:
      tags:
      - 'Testes'
      summary: 'Cria ou edita um modelo de teste'
      description: 'Cria ou edita um modelo de teste'
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/testes'
      responses:
        '200':
          description: OK
        '201':
          description: Teste criado com sucesso
        '404':           
          description: Não encontrado
        '400':
          description: Valor inválido
        '500':
          description: Falha na comunicação com o servidor
          
  /posicao/teste/{id_teste}:
    delete:
      tags:
        - "Testes"
      summary: "Deletar teste pelo id"
      description: "Deletar teste pelo id"
      parameters:
        - name: id_teste
          in: path
          required: true
          description: Id do teste a ser excluído.
          schema:
            type: integer
            format: int64
      responses: 
        '200':
          description: OK
        '404':           
          description: Não encontrado
        '400':
          description: Valor inválido
        '500':
          description: Falha na comunicação com o servidor
          
  /posicao/zeroPeca:
    post:
      tags: 
      - "Testes"
      summary: 'Define a posição do zero peça'
      description: 'Define a posição do zero peça'
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/coordenadasZeroPeca'
      responses:
        '201':
          description: Teste criado com sucesso
        '400':
          description: Valor inválido
        '500':
          description: Falha na comunicação com o servidor
          
  /posicao/zeroPeca/{id_teste}:
    get:
      tags: 
      - 'Testes'
      summary: 'Pega a posição do zero peça'
      description: 'Pega a posição do zero peça'
      parameters:
        - name: id_teste
          in: path
          required: true
          description: ID do teste para pegar o zero peça do teste.
          schema:
            type: integer
            format: int64
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/coordenadasZeroPeca'
        '400':
          description: Valor inválido
        '404':
          description: Teste não encontrado
        '500':
          description: Falha na comunicação com o servidor
      

components:
  schemas:
    testesArray:
      type: object
      properties:
        testes:
          type: array
          items:
            $ref: '#/components/schemas/testes'
            
    coordenadasZeroPeca:
      type: object
      properties:
        id_teste:
          type: integer
          format: int64
          example: 1
        x:
          type: integer
          format: int64
          example: 30
        y:
          type: integer
          format: int64
          example: 55
        z:
          type: integer
          format: int64
          example: 15
      
            
    coordenadas:
      type: object
      properties:
        x:
          type: integer
          format: int64
          example: 30
        y:
          type: integer
          format: int64
          example: 55
        z:
          type: integer
          format: int64
          example: 15
        r:
          type: integer
          format: int64
          example: 25
        t:
          type: integer
          format: int64
          example: 45
          
    
    testes:
      type: object
      properties:
        id:
          type: integer
          format: int64
          example: 1
        nome_teste:
          type: string
          format: utf-8
          example: teste-parado
        modelo:
          type: string
          format: utf-8
          example: modelo-produto
        coordenadas:
          type: array
          items:
            $ref: '#/components/schemas/coordenadas'
        zero_peca: 
          type: object
          $ref: '#/components/schemas/coordenadasZeroPeca'
            
      
